### ISSUE TITLE
Simconnect does not connect to msfs

### ISSUE THREAD

**Issue by Ludwig151** [Etouq/SimconnectServer#1]
Hello
Simconnect does not connect to msfs
Sim Connection State led remains hopelessly red...
It seems that this happens since the last updates of MSFS
Other applications that use simconnect (little navmap, spad.next) works well
Thanks
Ludwig

**Comment by Etouq** [comment]
Can you verify if it still happens with the latest version?

**Comment by Ludwig151** [comment]
It's ok with the last version
Thanks
